# Generated by Django 3.2 on 2024-03-16 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadSello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('horas', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=255)),
                ('facultad', models.CharField(max_length=125)),
                ('carrera', models.CharField(max_length=125)),
                ('horas_year', models.JSONField()),
                ('creditos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuarioSello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioSello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=255)),
                ('usuario_sello', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='actividades.tipousuariosello')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('usuario_sello', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='actividades.usuariosello')),
            ],
        ),
        migrations.CreateModel(
            name='MatriculaActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('actividad_sello', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='actividades.actividadsello')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='actividades.alumno')),
            ],
        ),
        migrations.AddField(
            model_name='actividadsello',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='actividades.area'),
        ),
        migrations.AddField(
            model_name='actividadsello',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='actividades.estado'),
        ),
        migrations.AddField(
            model_name='actividadsello',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='actividades.periodo'),
        ),
        migrations.AddField(
            model_name='actividadsello',
            name='usuario_sello',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='actividades.usuariosello'),
        ),
    ]
